# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_base_version=1.21.4
	minecraft_version=1.21.4
	yarn_mappings=1.21.4+build.2
	loader_version=0.16.9

# Mod Properties
	mod_version = 0.1.15
	maven_group = io.wispforest
	archives_base_name = lavender

# Dependencies
	# check this on https://fabricmc.net/develop
	fabric_version=0.112.0+1.21.4

	# https://maven.shedaniel.me/me/shedaniel/RoughlyEnoughItems-fabric/
	rei_version=18.0.796

	# https://maven.wispforest.io/#/releases/io/wispforest/owo-lib/
	owo_version=0.12.20+1.21.4

	# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
	modmenu_version=13.0.0-beta.1

	# https://maven.wispforest.io/#/releases/io/wispforest/lavender-md/core/
	lavender_md_version=0.1.2+1.21.2
